name: Deploy CarexLLC Backend Admin

on:
  push:
    branches:
      - main

jobs:
  web-deploy:
    name: Deploy Admin Panel via FTP
    runs-on: ubuntu-latest
    steps:
    - name: Get latest code
      uses: actions/checkout@v4
      
    - name: Sync All Files
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        local-dir: ./
        server-dir: ./public_html/admin.carexllc.com/
        exclude: |
          **/.git*
          **/.git*/**
          **/node_modules/**
          **/vendor/**
          .github/**
          public/assets/**
          public/uploads/**
          public/storage/**
